### ISSUE TITLE
JOSE paper folder is needed

### ISSUE THREAD

**Issue by mdogucu** [bayes-bats/tier2-freq-bayes#2]
I think it would be best to have folder for the paper documents. Perhaps naming the folder as `jose-paper` would make the most sense.
- [ ] create folder structure
- [ ] Update `README.md` to include JOSE paper.

**Comment by zdelrosario** [comment]
Hmm, I don't think we're allowed to do that. I tested moving the paper source to a subdirectory, and the OpenJournal's paper-checking [action failed](https://github.com/bayes-bats/tier2-freq-bayes/actions/runs/10223137485/job/28288984600).

**Comment by zdelrosario** [comment]
Oops, spoke too soon! Turns out TOJ's bot [finds our paper](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00251/jose.00251/10.21105.jose.00251.pdf) just fine. I updated our copy of their action and [it also builds](https://github.com/bayes-bats/tier2-freq-bayes/actions/runs/10223190279/job/28289120218) the paper when located in a subdirectory.
